// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edueauwukpktgihliape.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkdWVhdXd1a3BrdGdpaGxpYXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjU3ODUsImV4cCI6MjA2MjU0MTc4NX0.BqYqTdi12Gt5CtNTVYNHn0cQ9IXdrT0OEfRMAR4Edzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);